---
title: "Modown definition and usage"
author: "Vincent Bonhomme"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{modown}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## Rationale
Morphometrics data essentially consist of coordinates and, if any, associated covariates.

Existing morphometrics file format exist, eg `.tps`, `.nts`, `.xml`, etc. but (in y humble opinion) none is fully satisfactory.

I propose here the `.mod` file format along with R utilities.

Just like markdown, `Modown` has minimalist syntax and is easy to read/manipulate/write both for humans and machines.

Modown a pun on [markdown](https://daringfireball.net/projects/markdown/) and [Momocs](https://cran.r-project.org/web/packages/Momocs/index.html) and a tribute to [Motown](https://en.wikipedia.org/wiki/Motown).

## Specifications
`.mod` files are plain text files whose single line syntax fall within rules:

1. space-separated numbers (eg `-0.5 0.5`) stand for coordinates  (and other numeric data) in each dimension;
2. a word and a number or word (eg `size 3.14`) associate a covariate name and its value;
3. a single word (eg `ldk`) introduce a partition of coordinates;
4. a tilde (~) and word (eg `turtle1`:) names a shape name when several are collated in the same file.
5. nothing or something else (eg `# a comment`) is ignored.
